/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package CLIENT;


import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author sayali.shitole
 */
public class Add_project extends javax.swing.JFrame {

    
    /**
     * Creates new form Add_project
     */
    static String dept;
    static int id;
    static String pnm;
    static int pid;
    String n1="";
    public Add_project() {
    }

    public Add_project(String dept, int cid,String nam) {
        this.dept = dept;
        id = cid;
        n1=nam;
        initComponents();
         this.setTitle("Add New Project");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        pname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        sdate = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        edate = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tec = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        prodes = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 255));
        setForeground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(700, 700));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Palatino Linotype", 1, 18)); // NOI18N
        jLabel2.setText("Project Name:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 100, -1, -1));

        pname.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        getContentPane().add(pname, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 101, 250, -1));

        jLabel3.setFont(new java.awt.Font("Palatino Linotype", 1, 18)); // NOI18N
        jLabel3.setText("Start Date:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 168, -1, -1));

        sdate.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        getContentPane().add(sdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 169, 250, -1));

        jLabel4.setFont(new java.awt.Font("Palatino Linotype", 1, 18)); // NOI18N
        jLabel4.setText("End Date:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 239, -1, -1));

        edate.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        getContentPane().add(edate, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 250, -1));

        jLabel5.setFont(new java.awt.Font("Palatino Linotype", 1, 18)); // NOI18N
        jLabel5.setText("Technology:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 310, -1, -1));

        tec.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(tec, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 250, -1));

        jButton1.setFont(new java.awt.Font("Palatino Linotype", 1, 18)); // NOI18N
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 560, 99, -1));

        jButton2.setFont(new java.awt.Font("Palatino Linotype", 1, 18)); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 560, 104, -1));

        prodes.setColumns(20);
        prodes.setFont(new java.awt.Font("Palatino Linotype", 0, 12)); // NOI18N
        prodes.setRows(5);
        jScrollPane1.setViewportView(prodes);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, 250, 111));

        jLabel8.setFont(new java.awt.Font("Palatino Linotype", 1, 18)); // NOI18N
        jLabel8.setText("Project Description:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 380, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
        new OA_select("Operation",n1).setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String pnam = pname.getText();
        String stdat = sdate.getText();
        String eddate = edate.getText();
        String tech = tec.getText();
        String projdesc = prodes.getText();
        try {

            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/crm_project", "root", "root");

            PreparedStatement pr = (PreparedStatement) conn.prepareStatement("insert into add_proj " + "(proj_name,start_date,end_date,technology,proj_desc,client_id) values (?,?,?,?,?,?)");
            if (pnam.equals("") || stdat.equals("") || eddate.equals("") || tech.equals("") || projdesc.equals("")) {
                JOptionPane.showMessageDialog(null, "invalid ");

            } else {
                pr.setString(1, pnam);
                pr.setString(2, stdat);
                pr.setString(3, eddate);
                pr.setString(4, tech);
                pr.setString(5, projdesc);
                pr.setInt(6, id);
                pr.executeUpdate();
                JOptionPane.showMessageDialog(null, "Succesfully Register");

            }
            prodes.setText("");
            edate.setText("");
            //pname.setText("");
            sdate.setText("");
            tec.setText("");

        } catch (Exception e) {
            e.getMessage();
            System.out.println("" + e);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Add_project().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField edate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField pname;
    private javax.swing.JTextArea prodes;
    private javax.swing.JTextField sdate;
    private javax.swing.JTextField tec;
    // End of variables declaration//GEN-END:variables
}